---
version: 1

kind: experiment

environment:
  pytorch:
    n_workers: 1

declarations:
  batch_size_train: 128
  batch_size_test: 1000
  epochs: 5
  lr: 0.01
  train_steps: 400
  momentum: 0.5

build:
  image: 192.168.1.49:5000/pytorch/pytorch:v0.2
  #image: pytorch/pytorch:v0.2
  #build_steps:
  #  - pip install --no-cache-dir polyaxon-client==0.3.7

run:
  cmd: python distributed_run.py --batch-size={{ batch_size_train }} \
                                 --test-batch-size={{ batch_size_test }} \
                                 --epochs={{ epochs }} \
                                 --lr={{ lr }} \
                                 --momentum={{ momentum }} \
                                 --epochs={{ epochs }}
